### ISSUE TITLE
JS and CSS problems

### ISSUE THREAD

**Issue by ileicovici** [uran1980/yii2-translate-panel#1]
Hi!  I found an error in /uran1980/yii2-translate-panel/web/css/translate.css
the last line
/*# sourceMappingURL=translate.css.map */

GET http://a01.local/admin/assets/f3b0f869/css/translate.css.map 404 (Not Found)

and in /uran1980/yii2-translate-panel/web/js/translate.js
...
$form.ajaxSubmit({
...

error:
Uncaught TypeError: undefined is not a function                 translate.js:28

**Comment by uran1980** [comment]
Hi! I fix code a little bit.

Please try to run: ```composer update``` to update composer packages to latest versions.
Thanks for bug report!

**Comment by Tak0r** [comment]
/*# sourceMappingURL=translate.css.map */ error is normal and is only displayed because the developer tools look for some sass/less mapping you can simply ignore that one.

**Comment by mmx3** [comment]
The module is dependent on zelenin/yii2-i18n-module 0.1.* and that version of the zelenin module is no longer available.

**Comment by uran1980** [comment]
@mmx3 I don't have this problem. Can you provide your project ```composer.json``` file?

**Comment by mmx3** [comment]
Thanks, but I downloaded a copy from Github and will run it as a module. 

Gene Rodrigues

Email: gene.rodrigues@comcast.net
